# This workflow runs the unit tests for the xslim project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install onnx-graphsurgeon --no-deps
        grep -v nvidia-pyindex requirements.txt | grep -v onnx-graphsurgeon | grep -v '^torch' | pip install -r /dev/stdin
        pip install --no-deps -e .
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "test_*.py" -v
